import '../pages/styles.css'
import {Inter} from 'next/font/google'
import {GlobalContextProvider} from "@/app/context/store";
import Script from "next/script";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Pete and Karen\'s website',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode }>) {

    return (
        <html lang="en">
            <body className={inter.className}>
            <GlobalContextProvider>
                {children}
            </GlobalContextProvider>
            <Script src="https://kit.fontawesome.com/db0972ec9e.js" crossOrigin="anonymous"></Script>
            </body>
        </html>
)
}
